CREATE TABLE users (
  email VARCHAR(50) PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE students (
  email VARCHAR(50) PRIMARY KEY REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE,
  balance INT NOT NULL
);

CREATE TABLE staffs (
  email VARCHAR(50) PRIMARY KEY REFERENCES users(email) ON DELETE CASCADE ON UPDATE CASCADE,
  workplace VARCHAR(50) NOT NULL
);